package com.dehaat.config;

public enum ConfigProperties {
    ENV,
    APP_HASHCODE_DEHAAT_BUSINESS,
    APP_HASHCODE_DEHAAT_FARMER,
    MAILMAN_HOST,
    MAILMAN_SEND_TOKEN,
    RABBITMQ_CONNECT_URL,
    RABBITMQ_EXCHANGE,
    HONEYBADGER_SETAPIKEY
}
